# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 03:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.softdelete


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='t\xedtulo')),
                ('author_name', models.CharField(max_length=32, verbose_name='nome do autor')),
                ('author_email', models.EmailField(max_length=254, verbose_name='e-mail do autor')),
                ('text', models.TextField(verbose_name='texto')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_releases', to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(to='teams.Team', verbose_name='times envolvidos')),
            ],
            bases=(models.Model, utils.softdelete.SoftDeleteMixin),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='pergunta')),
                ('answer', models.TextField(blank=True, help_text='N\xe3o sabe a resposta ainda? Deixe em branco e algu\xe9m responder\xe1', verbose_name='resposta')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('press_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pr.PressRelease')),
            ],
            bases=(models.Model, utils.softdelete.SoftDeleteMixin),
        ),
    ]
