# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 03:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.softdelete


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nome')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_set', to=settings.AUTH_USER_MODEL, verbose_name='l\xedder da \xe1rea')),
            ],
            bases=(models.Model, utils.softdelete.SoftDeleteMixin),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nome')),
                ('image', models.ImageField(blank=True, help_text='Tire uma foto do seu time! Envie imagens quadradas (~500x500px)', upload_to=b'teams/', verbose_name='foto')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Area', verbose_name='\xe1rea')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_set', to=settings.AUTH_USER_MODEL, verbose_name='l\xedder do time')),
            ],
            options={
                'ordering': ('area', 'name'),
            },
            bases=(models.Model, utils.softdelete.SoftDeleteMixin),
        ),
    ]
