# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 03:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.softdelete


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome do pr\xeamio para o usu\xe1rio')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, utils.softdelete.SoftDeleteMixin),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome do pr\xeamio')),
                ('image', models.ImageField(help_text='Foto para simbolizar o pr\xeamio que a pessoa ganhou 128x128px.', upload_to=b'awards/', verbose_name='foto')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=(models.Model, utils.softdelete.SoftDeleteMixin),
        ),
        migrations.AddField(
            model_name='accountaward',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.Award'),
        ),
        migrations.AddField(
            model_name='accountaward',
            name='awarded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
